#%RAML 1.0 NamedExample
value:
  subscription_id: 1234
  delay_type: "delayed"
  email_sent: true
  delay_reason: "Got delayed due to bad weather"
  delay_time: 10
  service_id: "SE345436437567"
  creation_date: 2015-07-04T21:00:00
