#%RAML 1.0 NamedExample
description: "Example Data for Subscription for Alert notitication"
value:
  -
    sid: 123
    uid: "00u1s6qevfpVw3Yrz5d7"
    status: "Active"
    source_location: "ABW"
    destination_location: "PLU"
    from_time: 12:30:00
    to_time: 16:00:00
    advance_notify_time_min: 30
    creation_timestamp: 2015-07-04T21:00:00
    updated_timestamp: 2015-07-04T21:00:00
    alert_notification: true
  -
    sid: 154
    uid: "00u1s6qevfpVw34537"
    status: "Active"
    source_location: "ABW"
    destination_location: "PLU"
    from_time: 12:30:00
    to_time: 16:00:00
    advance_notify_time_min: 60
    creation_timestamp: 2015-07-04T21:00:00
    updated_timestamp: 2015-07-04T21:00:00
    alert_notification: false