#%RAML 1.0 NamedExample
description: "The example for accepted user input"
value:
  id: 00u1s6qevfpVw3Yrz5d7
  firstName: "Sara"
  lastName: "Lee"
  email: "sara.lee@example.com"
  login: "sara.lee"
  mobilePhone: "125"
  created: 2002-10-02T10:00:00-05:00
  lastUpdated: 2002-10-02T10:00:00-05:00
  status: "Active"